version: 1.1.0

__metadata__:

modifiers:
    - !LearningRateFunctionModifier
        cycle_epochs: 1.0
        end_epoch: 3.0
        final_lr: 0.01
        init_lr: 0
        lr_func: linear
        param_groups: [0, 1]
        start_epoch: 0.0
        update_frequency: -1.0

    - !LearningRateFunctionModifier
        cycle_epochs: 1.0
        end_epoch: 3.0
        final_lr: 0.01
        init_lr: 0.1
        lr_func: linear
        param_groups: [2]
        start_epoch: 0.0
        update_frequency: -1.0

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.4685
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.8.cv2.conv.weight', 'model.12.cv2.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.5217
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.4.cv2.conv.weight', 'model.15.cv2.conv.weight', 'model.22.cv2.0.2.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.4095
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.6.cv1.conv.weight', 'model.8.cv1.conv.weight', 'model.18.cv1.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.3438
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.0.conv.weight', 'model.2.cv1.conv.weight', 'model.15.cv1.conv.weight', 'model.22.cv2.1.2.weight', 'model.22.cv3.1.2.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.2709
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.2.cv2.conv.weight', 'model.4.cv1.conv.weight', 'model.22.cv3.0.2.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.0999
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.2.m.0.cv2.conv.weight', 'model.4.m.0.cv1.conv.weight', 'model.4.m.0.cv2.conv.weight', 'model.4.m.1.cv2.conv.weight', 'model.6.m.0.cv2.conv.weight', 'model.6.m.1.cv1.conv.weight', 'model.6.m.1.cv2.conv.weight', 'model.8.m.0.cv2.conv.weight', 'model.9.cv1.conv.weight', 'model.15.m.0.cv1.conv.weight', 'model.22.cv2.0.0.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.9015
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.22.cv2.1.0.conv.weight', 'model.22.cv2.2.0.conv.weight', 'model.22.cv3.0.1.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.7458
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.16.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.6125
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.9.cv2.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.8905
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.22.cv3.2.0.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.5695
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.3.conv.weight', 'model.6.cv2.conv.weight', 'model.18.cv2.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.8146
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.1.conv.weight', 'model.7.conv.weight', 'model.19.conv.weight', 'model.21.m.0.cv2.conv.weight', 'model.22.cv3.1.0.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.6861
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.5.conv.weight', 'model.21.cv1.conv.weight', 'model.21.cv2.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !GMPruningModifier
        end_epoch: 50.0
        final_sparsity: 0.1899
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.8.m.0.cv1.conv.weight', 'model.12.cv1.conv.weight', 'model.15.m.0.cv2.conv.weight', 'model.22.cv2.0.1.conv.weight', 'model.22.cv2.2.1.conv.weight', 'model.22.cv3.0.0.conv.weight']
        start_epoch: 4.0
        update_frequency: 1

    - !EpochRangeModifier
        end_epoch: 90.0
        start_epoch: 0.0

    - !LearningRateFunctionModifier
        cycle_epochs: 1.0
        end_epoch: 90.0
        final_lr: 0.0002
        init_lr: 0.01
        lr_func: linear
        start_epoch: 3.0
        update_frequency: -1.0
