"""
All constants used in the project
"""
# UI Parameters
LCD_RESOLUTION = (1024, 600)
CAMERA_RESOLUTION = (640, 480)
CAMERA_DISPLAY_SIZE = (480, 360)
TRAINING_MODE_CAMERA_SIZE = (720, 540)
CAMERA_FRAMERATE = 5
FPS_FONT_SIZE = 30
UI_FRAMERATE = 30
WIDGET_PADDING = 10
STAT_REFRESH_INTERVAL = 3000
BG_COLOUR = (128, 128, 128)
THEMEJSON = "./src/common/theme.json"
THEMEPARAMS = {
    "FONTSIZE" : 20,
    "labelTextColour" : "#FFFFFF"
}
SHOW_CURSOR = True
# Custom Pygame Parameters
TOGGLE_TRUE_COLOUR = "#23C552"
TOGGLE_FALSE_COLOUR = "#F84F31"
TOGGLE_HOVER_COLOUR = "#AEAEAE"
# GPIO Parameters
GPIO_PINS = {
    "MOSFET_CONTROL_PIN" : 18
}
MOSFET_FREQ = 1000
LED_BRIGHTNESS = 0
